FROM php:8.4-fpm-alpine

# build + runtime
RUN set -eux; \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers postgresql-dev oniguruma-dev; \
    apk add --no-cache postgresql-libs oniguruma

# расширения (минимум для Laravel)
RUN docker-php-ext-install pdo_pgsql mbstring

# xdebug (только dev)
RUN pecl install xdebug \
 && docker-php-ext-enable xdebug \
 && { \
      echo 'xdebug.mode=${XDEBUG_MODE:-debug}'; \
      echo 'xdebug.start_with_request=${XDEBUG_START_WITH_REQUEST:-trigger}'; \
      echo 'xdebug.client_host=${XDEBUG_CLIENT_HOST:-host.docker.internal}'; \
      echo 'xdebug.client_port=${XDEBUG_CLIENT_PORT:-9003}'; \
      echo 'xdebug.log_level=${XDEBUG_LOG_LEVEL:-0}'; \
    } > /usr/local/etc/php/conf.d/zz-xdebug.ini

# Dev OPCache — мгновенно видеть изменения
RUN { \
      echo 'opcache.enable=1'; \
      echo 'opcache.validate_timestamps=1'; \
      echo 'opcache.revalidate_freq=0'; \
    } > /usr/local/etc/php/conf.d/opcache-dev.ini

# подчистить build-deps — минус ~200–300 МБ
RUN apk del .build-deps && pecl clear-cache || true

WORKDIR /var/www/html
