services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      php-fpm:
        condition: service_started
    restart: unless-stopped
    networks:
      - frontend_net
      - backend_net
  php-fpm:
    build:
      context: ./docker/php
    container_name: php-fpm
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    env_file:
      - env/.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend_net
  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'
      - 'composer_cache:/tmp/composer-cache'
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    networks:
      - backend_net
  artisan:
    build:
      context: ./docker/php
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'
    entrypoint: ['php', 'artisan']
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_net
  db:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - env/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped
    networks:
      - backend_net

volumes:
  postgres_data:
  composer_data:
  composer_cache:

networks:
  frontend_net:
    driver: bridge
    name: frontend_net
  backend_net:
    driver: bridge
    name: backend_net
